In [1]:
import numpy as np

In [2]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.array([1,1,1,1,1,1,1,1])

array([1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
np.array([range(i,i+10) for i in [1,2,3,4,5,6]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [5]:
np.array([range(i,i+12) for i in (10,10)])

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [6]:
np.array([i for i in range(12)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.array(range(99))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [8]:
l = ['a','b','c','d']
np.array(l)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [9]:
a = [i*2 for i in range(50)]
np.array(a)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [10]:
np.ones(12,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
np.empty([2,2])


array([[2.12199579e-314, 0.00000000e+000],
       [6.30427764e-321, 1.24985552e-311]])

np.empty??

In [12]:
np.array([[1,2,3],[7,8,9]])

array([[1, 2, 3],
       [7, 8, 9]])

In [13]:
np.array([
    [1,2,3],
    [4,2,0],
    [2,3,4]
])

array([[1, 2, 3],
       [4, 2, 0],
       [2, 3, 4]])

In [14]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.ones(10,dtype=int,order='F')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones((4,6),dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.full((2,5),23,dtype=int)

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [20]:
np.array([(i,i*2,i*3,i*4,i*5,i*6,i*7,i*8,i*9,i*10) for i in range(10)])

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81, 90]])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
arr = np.full((4,5),7,dtype=int)

In [23]:
arr

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [24]:
arr.ndim

2

In [25]:
arr.size


20

In [26]:
arr.dtype

dtype('int32')

In [27]:
arr.shape

(4, 5)

In [28]:
arr.itemsize

4

In [29]:
np.random.seed(0)
arr2 = np.random.randint(20, size=(3,4),dtype=int)

In [30]:
print(arr2)

[[12 15  0  3]
 [ 3  7  9 19]
 [18  4  6 12]]


In [31]:
print("Array dimension is ", arr2.ndim)
print("Array data type is ", arr2.dtype)
print("Array size is ", arr2.size)
print("Array datatype size is ", arr2.itemsize)
print("Array Shape is ", arr2.shape)
print("Array Total byte size is ", arr2.nbytes)



Array dimension is  2
Array data type is  int32
Array size is  12
Array datatype size is  4
Array Shape is  (3, 4)
Array Total byte size is  48


In [32]:
arr2[1,1]

7

In [33]:
arr2[2,3]

12

In [36]:
np.random.randint(12, dtype=int)

1

In [48]:
x1 = [3,1,4,6,44,12,8,0,13]

In [38]:
x1

[3, 1, 4, 6, 44, 12, 8, 0, 13]

In [39]:
x1[0]


3

In [40]:
x1[-2]

0

In [41]:
# x1 = [3,  1,  4, 6, 44, 12,  8,  0,  13]
#index
# x1 = [0,  1,  2, 3,  4,  5,  6,  7,  8 ]
# x1 = [-9 -8  -7 -6  -5  -4, -3, -2, -1 ]


In [42]:
x1[-5]

44

In [43]:
x1[-8]

1

In [50]:
x1[1] = 77

In [45]:
x1

[3, 77, 4, 6, 44, 12, 8, 0, 13]

In [46]:
x1 = 4

In [49]:
x1

[3, 1, 4, 6, 44, 12, 8, 0, 13]

In [52]:
x1

[3, 77, 4, 6, 44, 12, 8, 0, 13]

In [53]:
x1[1] = 33.333

In [54]:
x1[1]

33.333

In [55]:
x1

[3, 33.333, 4, 6, 44, 12, 8, 0, 13]

In [56]:
x = np.array([1,2,3,4,5])

In [57]:
x

array([1, 2, 3, 4, 5])

In [58]:
x[1] = 1.222

In [59]:
x

array([1, 1, 3, 4, 5])