In [38]:
print("Hello, World!")

Hello, World!


In [5]:
def printname(name):
    print("Your name is" , name) 

In [7]:
 printname("Sabin Bajracharya")

Your name is Sabin Bajracharya


In [9]:
def square(number):
    print("Calculating the square of the number")
    return number ** 2

In [37]:
a = int(input("Enter integer number::"))
print(square(a))

Enter integer number::3
Calculating the square of the number
9


In [16]:
def myFunction():
    print("Inside the myFunction")
    
myFunction()

Inside the myFunction


In [18]:
def printString(str):
    print("The enter string is ", str)

In [19]:
printString("Sabin")
printString("Hello")
printString("Sabin is my name")
printString("I am practising function")

The enter string is  Sabin
The enter string is  Hello
The enter string is  Sabin is my name
The enter string is  I am practising function


In [22]:
def multipleArguments(fname,lname,address,telephone,email):
    print("Your name is " + fname + " " + lname)
    print("Address:: " + address)
    print("Telephone:: " , telephone)
    print("Email:: " + email)

In [23]:
multipleArguments("sabin","Bajracharya","Lagan Tole,Kathmandu,Nepal",215276,"sabin1129@hotmail.com")

Your name is sabin Bajracharya
Address:: Lagan Tole,Kathmandu,Nepal
Telephone::  215276
Email:: sabin1129@hotmail.com


In [26]:
def array(*args):
    for x in args:
        print(x)

In [27]:
array("Sabin","Rabin","Harry","Sangamita")

Sabin
Rabin
Harry
Sangamita


In [29]:
def sumIntegers(*num):
    total = 0
    for x in num:
        total = total + x
    return total

In [30]:
print("Sum of the input number is ", sumIntegers(1,1,1,2,3))

Sum of the input number is  8


In [33]:
def max(a,b):
    m = 0
    if a > b:
        m = a
    else:
        m = b
    return m 

In [1]:
print("Max is ", max(15,10))

Max is  15


In [2]:
help(len)
    
        

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [3]:
len?

In [4]:
l=[1,2,3,4,5]

In [26]:
l.insert?


In [7]:
l.insert(2,100)

In [14]:
l?

In [10]:
l.insert(1,99)

In [13]:
l.insert(1,23)

In [15]:
list()

[]

In [16]:
a = list()

In [24]:
a??


In [22]:
maxi?


In [29]:
def maxi(a,b):
    """ Function to return the maximum value among 2 values """
    m = 0
    if a > b:
        m = a
    else:
        m = b
    return m 

In [30]:
maxi??

In [31]:
maxi?

In [32]:
len??

In [39]:
import numpy
numpy.__version__

'1.21.4'

In [40]:
import numpy as np

In [41]:
np?


In [42]:
result = 0
for i in range(100):
    result += i


In [43]:
result?


In [57]:
x=12
print("X is ", x)


X is  12


In [60]:
x = "Hello"
print("X is ", x)

X is  Hello


In [61]:
x?

In [62]:
I = list(range(20))
I

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [65]:
type(I[5])

int

In [69]:
I = [1,'a',2.334,"Hello",2]
    

In [70]:
I

[1, 'a', 2.334, 'Hello', 2]

In [74]:
type(I[0])

int

In [75]:
type(I[2])

float

In [79]:
type(I[1])

str

In [78]:
[type(item) for item in I]

[int, str, float, str, int]

In [81]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [82]:
np.array([1,2.3,4,56])

array([ 1. ,  2.3,  4. , 56. ])

In [89]:
np.array([range(i,i+10) for i in [1,3,5,7]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [86]:
np?
