In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
for i in a:
    print(a[i-1])

1
2
3
4
5


In [5]:
for i in a:
    print(type(a[i-1]))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [13]:
sum = 0
for i in a:
    sum = sum + a[i-1]

print("sum = ",sum)

sum =  15


In [38]:
x1 = np.array([1,2,3,4.5,6])

##### x1

In [39]:
type(x1)

numpy.ndarray

In [40]:
type(x1[0])

numpy.float64

In [41]:
farray = np.array([1,2,3,4,5],dtype='float32')

In [42]:
farray


array([1., 2., 3., 4., 5.], dtype=float32)

In [43]:
type(farray)

numpy.ndarray

In [44]:
type(farray[1])

numpy.float32

In [45]:
twod = np.array([range(i,i+4) for i in [4,4,4,4]])

In [46]:
twod

array([[4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [67]:
arr1 = np.array([range(i,i+10)for i in [1,5,10]])

In [65]:
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [74]:
zero = np.zeros(10,dtype='int32')

In [71]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
type(zero[2])

numpy.int32

In [83]:
one = np.ones((4,5),dtype='int32')

In [92]:
for i in range(4):
    print("[",end="")
    for j in range(5):
        print(one[i][j],end="")
        if (j!=4):
            print(",",end="")
    print("]")    

[1,1,1,1,1]
[1,1,1,1,1]
[1,1,1,1,1]
[1,1,1,1,1]


In [84]:
one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [93]:
np.full((3,6),12)

array([[12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12]])