In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [2]:
l = [1,2,3]
l.insert?

In [3]:
l?

In [5]:
def square(a):
    """ Return the square value of passed arguments """
    return a*a

In [6]:
square?

In [7]:
square(3)

9

In [8]:
result = 0
for i in range(100):
    result = result + i

print(result)

4950


In [12]:
l = [1,2,3,4,5,6,7,8,9,10]
l2 = [str(c) for c in l]

In [15]:
for i in l2:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [16]:
l3 = [101,"Sabin",35,'M',"sabin@yahoo.com",78.5]
for i in l3:
    print(type(i))

<class 'int'>
<class 'str'>
<class 'int'>
<class 'str'>
<class 'str'>
<class 'float'>


In [18]:
#creating array
import numpy as np
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
sum = 0
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr1:
    sum = sum + i

print("The sum of first 10 number is ",sum,"Thank You")

The sum of first 10 number is  55 Thank You


In [27]:
#two dimensional array definition
twoD = [[1,2,3,4],[4,3,2,1],[3,3,4,5]]
print(twoD)

([1, 2, 3, 4], [4, 3, 2, 1], [3, 3, 4, 5])


In [32]:
twoD = np.array([range(i,i+10) for i in [1,2,3,4,5]])

In [33]:
print(twoD)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]]
