In [7]:
import numpy
numpy.__version__

'1.21.4'

In [10]:
import numpy as np
np??


In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
a = np.array([1,2,3,4,5.5])
a

array([1. , 2. , 3. , 4. , 5.5])

In [15]:
a = np.array([1,2,3,4,5.5],dtype='float32')
a


array([1. , 2. , 3. , 4. , 5.5], dtype=float32)

In [16]:
a?


In [18]:
a = np.array([range(i,i+5) for i in [1,1,1]])
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [21]:
a = np.zeros(50, dtype="float32")
a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [26]:
a = np.zeros(2,dtype="int")

In [27]:
a


array([0, 0])

In [28]:
a = np.ones((4,4),dtype=int)

In [29]:
a


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
a = np.full((4,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [32]:
a = np.array([(i,i*i) for i in range(1,10)])
a

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36],
       [ 7, 49],
       [ 8, 64],
       [ 9, 81]])